Add vue-class-components support via loader option
intlify/bundle-tools pull request #75
Opened 2021-12-14 14:27 UTC by SniperJoe

Issue: https://github.com/intlify/bundle-tools/issues/74

2021-12-14 15:11 UTC, kazupon requested changes
Thank you for your contribution!
Welcome! :)

I have a request.
Could you add the unit test, please? 🙏 
We need the code to verify that it is working correctly.

2021-12-15 12:46 UTC, SniperJoe commented
@kazupon done. 
I'm not familiar with snapshot testing, but I hope everything is fine :)

2021-12-16 03:57 UTC, kazupon commented
@SniperJoe 
Thank you very much!

2021-12-16 03:57 UTC, kazupon approved these changes

2021-12-16 03:58 UTC, merged